theta=0:2*pi/32:2*pi-2*pi/32
subplot(5,1,1)
plot(theta,sin(theta));
xlabel('theta')
ylabel('amplitude')
subplot(5,1,2)
plot(theta,sin(33*theta));
xlabel('theta')
ylabel('amplitude')
subplot(5,1,3)
plot(theta,sin(31*theta));
xlabel('theta')
ylabel('amplitude')
subplot(5,1,4)
plot(theta,sin(3*theta));
xlabel('theta')
ylabel('amplitude')
subplot(5,1,5)
plot(theta,sin(67*theta));
xlabel('theta')
ylabel('amplitude')